/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedBelgelerRouteImport } from './routes/_authenticated/belgeler'
import { Route as AuthenticatedDispatcherlarRouteImport } from './routes/_authenticated/dispatcherlar'
import { Route as AuthenticatedEkiplerRouteImport } from './routes/_authenticated/ekipler'
import { Route as AuthenticatedGorevlerRouteImport } from './routes/_authenticated/gorevler'
import { Route as AuthenticatedPanoRouteImport } from './routes/_authenticated/pano'
import { Route as AuthenticatedRotalarRouteImport } from './routes/_authenticated/rotalar'
import { Route as AuthenticatedSohbetRouteImport } from './routes/_authenticated/sohbet'
import { Route as AuthenticatedSuruculerRouteImport } from './routes/_authenticated/suruculer'
import { Route as AuthenticatedYoneticiRouteImport } from './routes/_authenticated/yonetici'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBelgelerRoute = AuthenticatedBelgelerRouteImport.update({
  id: '/belgeler',
  path: '/belgeler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatcherlarRoute =
  AuthenticatedDispatcherlarRouteImport.update({
    id: '/dispatcherlar',
    path: '/dispatcherlar',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEkiplerRoute = AuthenticatedEkiplerRouteImport.update({
  id: '/ekipler',
  path: '/ekipler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGorevlerRoute = AuthenticatedGorevlerRouteImport.update({
  id: '/gorevler',
  path: '/gorevler',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPanoRoute = AuthenticatedPanoRouteImport.update({
  id: '/pano',
  path: '/pano',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotalarRoute = AuthenticatedRotalarRouteImport.update({
  id: '/rotalar',
  path: '/rotalar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSohbetRoute = AuthenticatedSohbetRouteImport.update({
  id: '/sohbet',
  path: '/sohbet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSuruculerRoute = AuthenticatedSuruculerRouteImport.update({
  id: '/suruculer',
  path: '/suruculer',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedYoneticiRoute = AuthenticatedYoneticiRouteImport.update({
  id: '/yonetici',
  path: '/yonetici',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/belgeler': typeof AuthenticatedBelgelerRoute
  '/dispatcherlar': typeof AuthenticatedDispatcherlarRoute
  '/ekipler': typeof AuthenticatedEkiplerRoute
  '/gorevler': typeof AuthenticatedGorevlerRoute
  '/pano': typeof AuthenticatedPanoRoute
  '/rotalar': typeof AuthenticatedRotalarRoute
  '/sohbet': typeof AuthenticatedSohbetRoute
  '/suruculer': typeof AuthenticatedSuruculerRoute
  '/yonetici': typeof AuthenticatedYoneticiRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/belgeler': typeof AuthenticatedBelgelerRoute
  '/dispatcherlar': typeof AuthenticatedDispatcherlarRoute
  '/ekipler': typeof AuthenticatedEkiplerRoute
  '/gorevler': typeof AuthenticatedGorevlerRoute
  '/pano': typeof AuthenticatedPanoRoute
  '/rotalar': typeof AuthenticatedRotalarRoute
  '/sohbet': typeof AuthenticatedSohbetRoute
  '/suruculer': typeof AuthenticatedSuruculerRoute
  '/yonetici': typeof AuthenticatedYoneticiRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/belgeler': typeof AuthenticatedBelgelerRoute
  '/_authenticated/dispatcherlar': typeof AuthenticatedDispatcherlarRoute
  '/_authenticated/ekipler': typeof AuthenticatedEkiplerRoute
  '/_authenticated/gorevler': typeof AuthenticatedGorevlerRoute
  '/_authenticated/pano': typeof AuthenticatedPanoRoute
  '/_authenticated/rotalar': typeof AuthenticatedRotalarRoute
  '/_authenticated/sohbet': typeof AuthenticatedSohbetRoute
  '/_authenticated/suruculer': typeof AuthenticatedSuruculerRoute
  '/_authenticated/yonetici': typeof AuthenticatedYoneticiRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/belgeler'
    | '/dispatcherlar'
    | '/ekipler'
    | '/gorevler'
    | '/pano'
    | '/rotalar'
    | '/sohbet'
    | '/suruculer'
    | '/yonetici'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/belgeler'
    | '/dispatcherlar'
    | '/ekipler'
    | '/gorevler'
    | '/pano'
    | '/rotalar'
    | '/sohbet'
    | '/suruculer'
    | '/yonetici'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/belgeler'
    | '/_authenticated/dispatcherlar'
    | '/_authenticated/ekipler'
    | '/_authenticated/gorevler'
    | '/_authenticated/pano'
    | '/_authenticated/rotalar'
    | '/_authenticated/sohbet'
    | '/_authenticated/suruculer'
    | '/_authenticated/yonetici'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/belgeler': {
      id: '/_authenticated/belgeler'
      path: '/belgeler'
      fullPath: '/belgeler'
      preLoaderRoute: typeof AuthenticatedBelgelerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatcherlar': {
      id: '/_authenticated/dispatcherlar'
      path: '/dispatcherlar'
      fullPath: '/dispatcherlar'
      preLoaderRoute: typeof AuthenticatedDispatcherlarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ekipler': {
      id: '/_authenticated/ekipler'
      path: '/ekipler'
      fullPath: '/ekipler'
      preLoaderRoute: typeof AuthenticatedEkiplerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gorevler': {
      id: '/_authenticated/gorevler'
      path: '/gorevler'
      fullPath: '/gorevler'
      preLoaderRoute: typeof AuthenticatedGorevlerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pano': {
      id: '/_authenticated/pano'
      path: '/pano'
      fullPath: '/pano'
      preLoaderRoute: typeof AuthenticatedPanoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotalar': {
      id: '/_authenticated/rotalar'
      path: '/rotalar'
      fullPath: '/rotalar'
      preLoaderRoute: typeof AuthenticatedRotalarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/sohbet': {
      id: '/_authenticated/sohbet'
      path: '/sohbet'
      fullPath: '/sohbet'
      preLoaderRoute: typeof AuthenticatedSohbetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/suruculer': {
      id: '/_authenticated/suruculer'
      path: '/suruculer'
      fullPath: '/suruculer'
      preLoaderRoute: typeof AuthenticatedSuruculerRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/yonetici': {
      id: '/_authenticated/yonetici'
      path: '/yonetici'
      fullPath: '/yonetici'
      preLoaderRoute: typeof AuthenticatedYoneticiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBelgelerRoute: typeof AuthenticatedBelgelerRoute
  AuthenticatedDispatcherlarRoute: typeof AuthenticatedDispatcherlarRoute
  AuthenticatedEkiplerRoute: typeof AuthenticatedEkiplerRoute
  AuthenticatedGorevlerRoute: typeof AuthenticatedGorevlerRoute
  AuthenticatedPanoRoute: typeof AuthenticatedPanoRoute
  AuthenticatedRotalarRoute: typeof AuthenticatedRotalarRoute
  AuthenticatedSohbetRoute: typeof AuthenticatedSohbetRoute
  AuthenticatedSuruculerRoute: typeof AuthenticatedSuruculerRoute
  AuthenticatedYoneticiRoute: typeof AuthenticatedYoneticiRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBelgelerRoute: AuthenticatedBelgelerRoute,
  AuthenticatedDispatcherlarRoute: AuthenticatedDispatcherlarRoute,
  AuthenticatedEkiplerRoute: AuthenticatedEkiplerRoute,
  AuthenticatedGorevlerRoute: AuthenticatedGorevlerRoute,
  AuthenticatedPanoRoute: AuthenticatedPanoRoute,
  AuthenticatedRotalarRoute: AuthenticatedRotalarRoute,
  AuthenticatedSohbetRoute: AuthenticatedSohbetRoute,
  AuthenticatedSuruculerRoute: AuthenticatedSuruculerRoute,
  AuthenticatedYoneticiRoute: AuthenticatedYoneticiRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
